In [4]:
# The full CNN code!
####################
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from tensorflow.keras.utils import to_categorical



In [8]:
from keras.datasets import mnist

In [9]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()


AttributeError: module 'keras.datasets.mnist' has no attribute 'train_images'

In [10]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [11]:
# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5



Epoch 1/3
1875/1875 [==============================] - 20s 8ms/step - loss: 0.3381 - accuracy: 0.9025 - val_loss: 0.2010 - val_accuracy: 0.9425
Epoch 2/3
1875/1875 [==============================] - 15s 8ms/step - loss: 0.1749 - accuracy: 0.9504 - val_loss: 0.1411 - val_accuracy: 0.9600
Epoch 3/3
1875/1875 [==============================] - 15s 8ms/step - loss: 0.1300 - accuracy: 0.9629 - val_loss: 0.1124 - val_accuracy: 0.9651
[7 2 1 0 4]
[7 2 1 0 4]


In [12]:
# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)



In [13]:
num_filters = 8
filter_size = 3
pool_size = 2



In [14]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])



In [15]:
# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)



In [16]:
# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)



Epoch 1/3
1875/1875 [==============================] - 14s 7ms/step - loss: 0.3363 - accuracy: 0.9044 - val_loss: 0.1820 - val_accuracy: 0.9468
Epoch 2/3
1875/1875 [==============================] - 13s 7ms/step - loss: 0.1585 - accuracy: 0.9542 - val_loss: 0.1286 - val_accuracy: 0.9618
Epoch 3/3
1875/1875 [==============================] - 13s 7ms/step - loss: 0.1180 - accuracy: 0.9664 - val_loss: 0.1022 - val_accuracy: 0.9693


In [17]:
# Save the model to disk.
model.save_weights('cnn.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')



In [18]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])



In [19]:
# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]



[7 2 1 0 4]


In [20]:
# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
